### PR TITLE
Increased MAX_ARENAS from 64 to 256

### PR DESCRIPTION
**Pull request by Duk0**
Fixes "Max infos exceeded" message on opened callvote.
This allow add more custom maps to the maplist as well.

### CODE REVIEW

**Comment by MAN-AT-ARMS** [comment]
Out of range

**Comment by Duk0** [comment]
Without this we can't add more custom maps. And maplist in callvote wouldn't show maps wich exceeded MAX_ARENAS count.

**Comment by MAN-AT-ARMS** [comment]
What do you mean you CAN'T add custom maps?

**Comment by fretn** [comment]
A lot of people have a huge number of custom maps but rtcwcoop is limited in the number of maps that it can show

**Comment by MAN-AT-ARMS** [comment]
I pushed commit 5b46346, which sets MAX_ARENA and MAX_BOTS to 1024 which are the Q3 values.
Hopefully we won't crash out the UI.

**Pull request closed without merging**
